name = "FFTransforms"
uuid = "41ee4b3b-6d90-492a-9c4b-6a995b15ca9c"
authors = ["Ethan Anderes <anderes@ucdavis.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
